import React,{useState} from 'react';
import{createRoot}from'react-dom/client';
import{Activity,ArrowUpRight,Bell,BookOpen,Check,ChevronRight,Clock,Command,FileText,Flame,Globe2,LayoutDashboard,PenLine,Radio,Search,Settings2,Sparkles,TrendingUp,Users,Zap}from'lucide-react';
import'./styles.css';

const topics=[
 {tag:'AI Agent',title:'AI 助手正在从“回答问题”走向“替你完成工作”',src:'全球科技',score:94,growth:'+286%',time:'18 分钟前',tone:'理性升温',color:'#ff7657'},
 {tag:'消费观察',title:'年轻人开始为“数字戒断”付费',src:'小红书 · 微博',score:88,growth:'+174%',time:'42 分钟前',tone:'讨论加速',color:'#c7f55c'},
 {tag:'出海',title:'中国小团队的下一站：一人公司全球化',src:'X · Product Hunt',score:84,growth:'+121%',time:'1 小时前',tone:'持续上行',color:'#72a7ff'},
 {tag:'职场',title:'不加班之后，管理者开始重新设计工作',src:'知乎 · 即刻',score:79,growth:'+93%',time:'2 小时前',tone:'稳定增长',color:'#ceb0ff'}
];
const styles=['深度洞察','故事叙事','犀利评论','温暖共鸣','知识科普'];

function Nav(){return <aside><div className="brand"><span>澎</span><b>澎湃台</b></div><nav>{[[LayoutDashboard,'今日脉搏'],[Radio,'热点雷达'],[PenLine,'智能创作'],[FileText,'内容资产'],[BookOpen,'发布中心']].map(([I,t],i)=><button className={i===0?'active':''} key={t}><I size={18}/>{t}{i===1&&<em>12</em>}</button>)}</nav><div className="asideFoot"><button><Settings2 size={18}/>工作台设置</button><div className="user"><div>光</div><span><b>光新工作室</b><small>专业版 · 运行良好</small></span></div></div></aside>}
function App(){const[style,setStyle]=useState('深度洞察');const[query,setQuery]=useState('');const[modal,setModal]=useState(false);const[toast,setToast]=useState('');const generate=()=>{setModal(true);setTimeout(()=>setToast('文章初稿已生成，已保留全部信源'),700)};return <div className="app"><Nav/><main><header><div><small>2026年8月1日 · 星期六</small><h1>早上好，今天有什么值得写？</h1></div><div className="actions"><button className="icon"><Search size={18}/></button><button className="icon"><Bell size={18}/><i/></button><button className="primary" onClick={generate}><Sparkles size={17}/>开始创作</button></div></header>
<section className="pulse"><div className="pulseTop"><div><span className="live"><i/>LIVE</span><p>全网热点脉搏</p></div><span>更新于 09:42</span></div><div className="pulseGrid"><div><strong>1,286</strong><span>今日追踪话题</span></div><div><strong>36</strong><span>正在快速升温</span></div><div><strong>8</strong><span>与你的领域匹配</span></div><div className="wave"><svg viewBox="0 0 300 62"><path d="M0 51 C35 45 45 50 65 33 S98 42 120 29 S151 36 174 16 S208 38 231 21 S266 18 300 5"/><path className="glow" d="M0 51 C35 45 45 50 65 33 S98 42 120 29 S151 36 174 16 S208 38 231 21 S266 18 300 5"/></svg><span><TrendingUp size={14}/>整体热度 +18.6%</span></div></div></section>
<div className="sectionHead"><div><h2>为你精选</h2><p>综合热度、增长速度与你的内容定位</p></div><button>查看全部热点 <ArrowUpRight size={15}/></button></div>
<section className="topics">{topics.map((t,i)=><article key={t.title} onClick={()=>setQuery(t.title)}><div className="rank">0{i+1}</div><div className="topicBody"><div className="meta"><span style={{'--c':t.color}}>{t.tag}</span><small>{t.src}</small></div><h3>{t.title}</h3><div className="metrics"><span><Flame size={14}/>热度 <b>{t.score}</b></span><span><TrendingUp size={14}/><b>{t.growth}</b></span><span><Clock size={14}/>{t.time}</span></div></div><div className="topicSide"><div className="score" style={{'--p':`${t.score*3.6}deg`}}><b>{t.score}</b></div><small>{t.tone}</small></div></article>)}</section>
<section className="create"><div className="createIntro"><span><Zap size={20}/></span><div><h2>把一个想法，变成一篇好文章</h2><p>输入主题，AI 会先研究信源、提炼观点，再按你的风格完成初稿。</p></div></div><div className="composer"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="例如：为什么越来越多人开始追求低欲望生活？"/><button onClick={generate} aria-label="生成文章"><ChevronRight/></button></div><div className="styleRow"><small>写作风格</small>{styles.map(s=><button onClick={()=>setStyle(s)} className={s===style?'selected':''} key={s}>{s===style&&<Check size={13}/>} {s}</button>)}</div></section>
</main>{modal&&<div className="overlay" onClick={()=>setModal(false)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setModal(false)}>×</button><span className="modalIcon"><Sparkles/></span><small>智能创作工作流</small><h2>{query||'AI 助手正在从“回答问题”走向“替你完成工作”'}</h2><div className="steps">{['检索并交叉验证 12 个信源','提炼 3 个差异化观点','按「'+style+'」生成初稿','事实与合规检查'].map((x,i)=><div className={i<3?'done':''} key={x}><span>{i<3?<Check size={14}/>:i+1}</span>{x}</div>)}</div><button className="publish" onClick={()=>setToast('已安全保存至微信公众号草稿箱')}><BookOpen size={17}/>保存到公众号草稿箱</button><p>发布前始终由你确认 · 不会自动群发</p></div></div>}{toast&&<div className="toast"><Check size={16}/>{toast}<button onClick={()=>setToast('')}>×</button></div>}</div>}
createRoot(document.getElementById('root')).render(<App/>);
